### REQUIRED SETTINGS ###

# Set a plain language title for the site.
title: US Gov Agency Browser Prototype test

# Write a short description for the site. This is used for "meta description."
description: Chekcing to see if potenial user testers can access browser prototypes hosted on Github Pages

# Enable for live hosting on GitHub Pages.
# It should start with a slash (/) and then match the name of your repository exactly.
baseurl: /browser-prototype-test

# =============================================================================

### CONTENT SETTINGS ###

# Change the image on the homepage.
# - You can use an absolute link to an existing image.
# - Or you can upload an image to the repository and use a relative link, starting with "../img/"
# - Make sure your filename doesn't have any spaces.
homepage-image: "https://unsplash.com/photos/H5h91CXv0E0"

# Define content collections
collections:
  resources:
    output: true

# =============================================================================

### OPTIONAL SETTINGS ###

# Set the language for the site. Used for "html lang." Default is English.
lang: en

# Add Google Analytics if needed. Replace placeholder with site ID.
ga: UA-XXXXX-Y

# Avoid GitHub API authentication when building locally. (Not working)
github: [metadata]

# Remove generation of additional style.css
theme: null
